apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: microservices-ingress
  namespace: dev # change to your environment
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - host: microservices.local # change to your domain or test host
      http:
        paths:
          - path: /alpha
            pathType: Prefix
            backend:
              service:
                name: alpha-service
                port:
                  number: 8080
          - path: /beta
            pathType: Prefix
            backend:
              service:
                name: beta-service
                port:
                  number: 8081
          - path: /gamma
            pathType: Prefix
            backend:
              service:
                name: gamma-service
                port:
                  number: 8082
